"""Health record assistant for safety-bounded report summaries."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from .events import append_event
from .papers import read_paper_text
from .paths import EVENTS_PATH, HEALTH_RECORDS_OUTPUT_DIR


SUPPORTED_HEALTH_SUFFIXES = {".pdf", ".txt", ".md"}


@dataclass(frozen=True)
class HealthReport:
    title: str
    source_path: Path
    report_path: Path
    indicators: dict[str, str]
    markdown: str


INDICATOR_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("血压", re.compile(r"血压\s*[:：]?\s*([0-9]{2,3}\s*/\s*[0-9]{2,3}\s*mmHg)", re.I)),
    ("空腹血糖", re.compile(r"空腹血糖\s*[:：]?\s*([0-9.]+\s*mmol/L)", re.I)),
    ("总胆固醇", re.compile(r"总胆固醇\s*[:：]?\s*([0-9.]+\s*mmol/L)", re.I)),
    (
        "低密度脂蛋白",
        re.compile(r"(?:低密度脂蛋白|LDL-C?)\s*[:：]?\s*([0-9.]+\s*mmol/L)", re.I),
    ),
    (
        "高密度脂蛋白",
        re.compile(r"(?:高密度脂蛋白|HDL-C?)\s*[:：]?\s*([0-9.]+\s*mmol/L)", re.I),
    ),
    ("甘油三酯", re.compile(r"甘油三酯\s*[:：]?\s*([0-9.]+\s*mmol/L)", re.I)),
    ("谷丙转氨酶", re.compile(r"(?:谷丙转氨酶|ALT)\s*[:：]?\s*([0-9.]+\s*U/L)", re.I)),
    ("体重指数", re.compile(r"(?:体重指数|BMI)\s*[:：]?\s*([0-9.]+)", re.I)),
]


def read_health_record_text(path: Path) -> str:
    """Read health record text from txt, Markdown, or PDF files."""
    if not path.exists():
        raise FileNotFoundError(f"Health record file not found: {path}")
    if path.suffix.lower() not in SUPPORTED_HEALTH_SUFFIXES:
        raise ValueError(f"Unsupported health record file type: {path.suffix}")
    return read_paper_text(path)


def infer_health_title(text: str, source_path: Path) -> str:
    """Infer a compact title from the first meaningful health record line."""
    for line in text.splitlines():
        candidate = line.strip().strip("# ")
        if 4 <= len(candidate) <= 80:
            return candidate
    return source_path.stem.replace("_", " ").replace("-", " ").title()


def extract_health_indicators(text: str) -> dict[str, str]:
    """Extract common checkup indicators from Chinese health record text."""
    indicators: dict[str, str] = {}
    for name, pattern in INDICATOR_PATTERNS:
        match = pattern.search(text)
        if match:
            indicators[name] = re.sub(r"\s+", " ", match.group(1)).strip()
    return indicators


def _indicator_notes(indicators: dict[str, str]) -> list[str]:
    notes: list[str] = []
    if "血压" in indicators:
        notes.append("血压指标建议结合多次家庭血压或门诊测量结果观察趋势。")
    if "空腹血糖" in indicators:
        notes.append("血糖指标建议结合饮食、运动、家族史和复查结果综合理解。")
    lipid_keys = {"总胆固醇", "低密度脂蛋白", "高密度脂蛋白", "甘油三酯"}
    if lipid_keys.intersection(indicators):
        notes.append("血脂相关指标可作为生活方式管理和心血管风险沟通的参考信息。")
    if "谷丙转氨酶" in indicators:
        notes.append("肝功能相关指标需要结合饮酒、用药、脂肪肝和既往病史等背景理解。")
    if not notes:
        notes.append("未识别到常见结构化指标，建议补充更完整的体检报告文本后重新分析。")
    return notes


def render_health_report(
    title: str,
    source_path: Path,
    indicators: dict[str, str],
    text: str,
) -> str:
    """Render a safety-bounded Markdown health summary."""
    indicator_lines = (
        "\n".join(f"- {name}: {value}" for name, value in indicators.items())
        if indicators
        else "- 未识别到常见指标。"
    )
    notes = "\n".join(f"- {note}" for note in _indicator_notes(indicators))
    excerpt = text[:900].strip()

    return f"""# Health Record Summary: {title}

## 1. Safety Notice

仅供健康信息整理与学习参考，不能替代执业医师诊断、治疗或处方。如有明显不适、急性症状或指标严重异常，请及时就医。

## 2. Source

- File: `{source_path}`
- Generated by: `agent_lab health analyze`

## 3. Extracted Indicators

{indicator_lines}

## 4. General Interpretation Notes

{notes}

## 5. Doctor Communication Checklist

- 建议与医生沟通这些指标是否需要复查、连续监测或结合其他检查判断。
- 准备近期饮食、运动、睡眠、用药和既往病史信息，帮助医生理解指标背景。
- 如果报告中有明确异常标记，请优先咨询专业医生，而不是自行用药或停药。

## 6. Lifestyle Information

- 保持规律作息、适量运动和均衡饮食通常有助于长期健康管理。
- 控盐、控糖、减少高油饮食和规律复查可作为与医生沟通前的基础信息准备。
- 本节不是个体化治疗方案，不提供药物、剂量或处方建议。

## 7. Source Excerpt

```text
{excerpt}
```
"""


def analyze_health_record(
    source_path: Path,
    *,
    output_dir: Path = HEALTH_RECORDS_OUTPUT_DIR,
    events_path: Path = EVENTS_PATH,
) -> HealthReport:
    """Analyze a health record and write a safety-bounded Markdown summary."""
    text = read_health_record_text(source_path)
    title = infer_health_title(text, source_path)
    indicators = extract_health_indicators(text)
    markdown = render_health_report(title, source_path, indicators, text)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"{source_path.stem}.md"
    report_path.write_text(markdown, encoding="utf-8")

    append_event(
        "health_record_analyzed",
        {
            "record": str(source_path),
            "title": title,
            "indicator_count": len(indicators),
        },
        events_path=events_path,
    )
    append_event(
        "health_report_generated",
        {
            "record": str(source_path),
            "title": title,
            "report_path": str(report_path),
        },
        events_path=events_path,
    )
    return HealthReport(
        title=title,
        source_path=source_path,
        report_path=report_path,
        indicators=indicators,
        markdown=markdown,
    )


def list_health_reports(output_dir: Path = HEALTH_RECORDS_OUTPUT_DIR) -> list[Path]:
    """Return generated Markdown health reports."""
    if not output_dir.exists():
        return []
    return sorted(output_dir.glob("*.md"))
