"""Paper reading assistant for research-note generation."""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .events import append_event
from .paths import EVENTS_PATH, PAPERS_OUTPUT_DIR

SUPPORTED_PAPER_SUFFIXES = {".pdf", ".txt", ".md"}


@dataclass(frozen=True)
class PaperNote:
    title: str
    source_path: Path
    note_path: Path
    word_count: int
    sections: dict[str, str]


def _collapse_whitespace(text: str) -> str:
    text = text.replace("\x00", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _read_pdf_with_pdftotext(path: Path) -> str | None:
    if shutil.which("pdftotext") is None:
        return None
    result = subprocess.run(
        ["pdftotext", str(path), "-"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout


def _read_pdf_with_python_libs(path: Path) -> str | None:
    try:
        from pypdf import PdfReader  # type: ignore
    except ImportError:
        PdfReader = None  # type: ignore

    if PdfReader is not None:
        reader = PdfReader(str(path))
        return "\n\n".join(page.extract_text() or "" for page in reader.pages)

    try:
        import fitz  # type: ignore
    except ImportError:
        return None

    with fitz.open(str(path)) as document:
        return "\n\n".join(page.get_text() for page in document)


def read_paper_text(path: Path) -> str:
    """Read paper text from Markdown, plain text, or PDF files."""
    if not path.exists():
        raise FileNotFoundError(f"Paper file not found: {path}")
    if path.suffix.lower() not in SUPPORTED_PAPER_SUFFIXES:
        raise ValueError(f"Unsupported paper file type: {path.suffix}")

    if path.suffix.lower() in {".txt", ".md"}:
        return _collapse_whitespace(path.read_text(encoding="utf-8"))

    text = _read_pdf_with_pdftotext(path) or _read_pdf_with_python_libs(path)
    if text is None:
        raise RuntimeError(
            "Could not extract PDF text. Install poppler-utils, pypdf, or PyMuPDF."
        )
    return _collapse_whitespace(text)


def infer_title(text: str, source_path: Path) -> str:
    """Infer a readable title from the first meaningful paper line."""
    for line in text.splitlines():
        candidate = line.strip().strip("# ")
        if 8 <= len(candidate) <= 180 and not candidate.lower().startswith("abstract"):
            return candidate
    return source_path.stem.replace("_", " ").replace("-", " ").title()


def _take_excerpt(text: str, max_chars: int = 900) -> str:
    compact = _collapse_whitespace(text)
    if len(compact) <= max_chars:
        return compact or "Not found in extracted text."
    return compact[:max_chars].rsplit(" ", 1)[0] + "..."


def _find_section(text: str, headings: list[str]) -> str:
    escaped = "|".join(re.escape(heading) for heading in headings)
    pattern = re.compile(
        rf"(?ims)^\s*(?:\d+(?:\.\d+)*\.?\s*)?({escaped})\s*$"
        rf"(.*?)(?=^\s*(?:\d+(?:\.\d+)*\.?\s*)?[A-Z][A-Za-z /&-]{{2,80}}\s*$|\Z)"
    )
    match = pattern.search(text)
    if not match:
        return ""
    return _take_excerpt(match.group(2))


def extract_sections(text: str) -> dict[str, str]:
    """Extract coarse paper sections for first-pass research notes."""
    abstract = _find_section(text, ["Abstract"])
    introduction = _find_section(text, ["Introduction", "Background"])
    method = _find_section(
        text,
        ["Method", "Methods", "Methodology", "Approach", "Proposed Method", "Model"],
    )
    experiments = _find_section(
        text,
        ["Experiments", "Experiment", "Evaluation", "Experimental Setup", "Results"],
    )
    conclusion = _find_section(text, ["Conclusion", "Conclusions", "Discussion"])
    limitations = _find_section(text, ["Limitation", "Limitations", "Threats to Validity"])

    fallback = _take_excerpt(text, 1200)
    return {
        "abstract": abstract or fallback,
        "background": introduction or abstract or fallback,
        "method": method or "Not found in extracted text.",
        "experiments": experiments or "Not found in extracted text.",
        "conclusion": conclusion or "Not found in extracted text.",
        "limitations": limitations or "Not explicitly discussed in extracted text.",
    }


def render_note(title: str, source_path: Path, text: str, sections: dict[str, str]) -> str:
    word_count = len(re.findall(r"\w+", text))
    return f"""# Paper Note: {title}

## 1. Basic Info
- Source: `{source_path}`
- Approx. word count: {word_count}
- Generated by: `agent_lab papers read`

## 2. Research Background
{sections["background"]}

## 3. Research Gap
- What problem does this paper try to solve?
- What limitation of prior work motivates this study?
- What is the claimed contribution?

## 4. Method
{sections["method"]}

## 5. Experiments
{sections["experiments"]}

## 6. Results and Conclusion
{sections["conclusion"]}

## 7. Limitations
{sections["limitations"]}

## 8. Research Discussion Questions
- What is the paper's strongest technical idea?
- Which assumption is most likely to fail in another dataset or setting?
- What experiment would you add if you were extending this work?

## 9. Research Follow-up Ideas
- What adjacent problem could this method be applied to?
- Which component could be replaced or simplified?
- What data, metric, or ablation would make the claim more convincing?

## 10. Concise Research Summary
This paper studies `{title}`. Use the extracted sections above to refine a concise research summary with evidence, limitations, and possible follow-up work.
"""


def generate_paper_note(
    source_path: Path,
    *,
    output_dir: Path = PAPERS_OUTPUT_DIR,
    events_path: Path = EVENTS_PATH,
) -> PaperNote:
    """Read a paper file and write a structured Markdown note."""
    text = read_paper_text(source_path)
    title = infer_title(text, source_path)
    sections = extract_sections(text)
    output_dir.mkdir(parents=True, exist_ok=True)
    note_path = output_dir / f"{source_path.stem}.md"
    note_path.write_text(render_note(title, source_path, text, sections), encoding="utf-8")

    word_count = len(re.findall(r"\w+", text))
    append_event(
        "paper_read",
        {
            "paper": str(source_path),
            "title": title,
            "word_count": word_count,
        },
        events_path=events_path,
    )
    append_event(
        "paper_note_generated",
        {
            "paper": str(source_path),
            "title": title,
            "note_path": str(note_path),
        },
        events_path=events_path,
    )
    return PaperNote(
        title=title,
        source_path=source_path,
        note_path=note_path,
        word_count=word_count,
        sections=sections,
    )


def generate_notes_for_folder(
    folder_path: Path,
    *,
    output_dir: Path = PAPERS_OUTPUT_DIR,
    events_path: Path = EVENTS_PATH,
) -> list[PaperNote]:
    """Generate notes for supported paper files in one folder."""
    if not folder_path.exists():
        raise FileNotFoundError(f"Paper folder not found: {folder_path}")
    if not folder_path.is_dir():
        raise NotADirectoryError(f"Paper folder is not a directory: {folder_path}")

    notes: list[PaperNote] = []
    for path in sorted(folder_path.iterdir()):
        if path.is_file() and path.suffix.lower() in SUPPORTED_PAPER_SUFFIXES:
            notes.append(generate_paper_note(path, output_dir=output_dir, events_path=events_path))
    return notes


def list_paper_notes(output_dir: Path = PAPERS_OUTPUT_DIR) -> list[Path]:
    """Return generated Markdown paper notes."""
    if not output_dir.exists():
        return []
    return sorted(output_dir.glob("*.md"))
